# Generated by Django 3.0.8 on 2020-07-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('estatus', models.CharField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_codigo', models.CharField(max_length=100)),
                ('estatus', models.CharField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gestiones',
            fields=[
                ('id_gestion', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField()),
                ('fch_gestion', models.DateField(auto_now_add=True)),
                ('hora_gestion', models.TimeField(auto_now_add=True)),
                ('id_codigo', models.IntegerField()),
                ('id_motivo', models.IntegerField()),
                ('descrip_gestion', models.TextField()),
                ('estatus', models.CharField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Motivos',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_motivo', models.CharField(max_length=100)),
                ('estatus', models.CharField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recordatorios',
            fields=[
                ('id_recordatorio', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField()),
                ('fch_recordatorio', models.DateField()),
                ('hora_recordatorio', models.TimeField()),
                ('descrip_recordatorio', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
