# Generated by Django 3.0.8 on 2020-07-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCobros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='Nacionalidad',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
