# Generated by Django 3.0.8 on 2020-07-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCobros', '0002_clientes_nacionalidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['id_cliente'], 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='clientes',
            name='imagencliente',
            field=models.ImageField(blank=True, upload_to='fotosclientes'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Nacionalidad',
            field=models.CharField(help_text='Ejemp: hondureño, estadounidense, canadiense', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Email Institucional'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estatus',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
