# Generated by Django 3.0.8 on 2020-08-01 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCobros', '0003_auto_20200730_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fch_modificacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField()),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
                'ordering': ['id_departamento'],
            },
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fch_modificacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField()),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Puestos',
                'ordering': ['id_puesto'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=35)),
                ('segundo_nombre', models.CharField(blank=True, max_length=35)),
                ('primer_apellido', models.CharField(max_length=35)),
                ('segundo_apellido', models.CharField(blank=True, max_length=35)),
                ('usuario', models.CharField(help_text='Ejemplo: nombre.apellido', max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('fch_ultimo_acceso', models.DateTimeField()),
                ('ip_ultimo_acceso', models.CharField(max_length=50)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fch_modificacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField()),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Departamentos')),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Puestos')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'ordering': ['primer_nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Codigos',
        ),
        migrations.DeleteModel(
            name='Gestiones',
        ),
        migrations.DeleteModel(
            name='Motivos',
        ),
        migrations.DeleteModel(
            name='Recordatorios',
        ),
        migrations.AddField(
            model_name='departamentos',
            name='id_puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Puestos'),
        ),
    ]
