# Generated by Django 3.0.8 on 2020-08-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCobros', '0004_auto_20200801_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='fch_modificacion',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='fch_modificacion',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='usuario_modificacion',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fch_modificacion',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
