# Generated by Django 3.0.8 on 2020-08-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCobros', '0005_auto_20200801_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='usuario_modificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='usuario_modificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usuario_modificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
