# Generated by Django 3.0.8 on 2020-08-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCobros', '0006_auto_20200801_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentos',
            name='id_puesto',
        ),
        migrations.AddField(
            model_name='puestos',
            name='id_departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Departamentos'),
            preserve_default=False,
        ),
    ]
