# Generated by Django 3.0.8 on 2020-08-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCobros', '0008_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_id', models.CharField(choices=[('1', 'Cédula de Identidad'), ('2', 'RTN'), ('3', 'Otro')], default='1', max_length=1, verbose_name='Tipo de Identificación')),
                ('identidad', models.CharField(blank=True, max_length=30)),
                ('fch_nacimiento', models.CharField(blank=True, max_length=30)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contacto', models.CharField(choices=[('Teléfono Trabajo', 'Teléfono Trabajo'), ('Teléfono Casa', 'Teléfono Casa'), ('Celular', 'Celular'), ('Dirección Casa', 'Dirección Casa'), ('Dirección Trabajo', 'Dirección Trabajo'), ('Correo', 'Correo')], default='Teléfono', max_length=35)),
                ('descripcion', models.TextField()),
                ('comentario', models.CharField(max_length=200)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Contactos Cliente',
                'ordering': ['tipo_contacto'],
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=450)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('nombre_contacto', models.CharField(blank=True, max_length=80)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'ordering': ['id_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('numero_producto', models.CharField(max_length=50)),
                ('mora_actual', models.IntegerField()),
                ('capital', models.IntegerField()),
                ('intereses', models.IntegerField()),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Clientes')),
            ],
            options={
                'verbose_name_plural': 'Productos Cliente',
                'ordering': ['descripcion'],
            },
        ),
        migrations.DeleteModel(
            name='prueba',
        ),
        migrations.AddField(
            model_name='clientes',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Empresas'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Usuarios'),
        ),
    ]
