# Generated by Django 3.0.8 on 2020-08-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCobros', '0009_auto_20200802_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripción', models.CharField(max_length=100)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Códigos',
                'ordering': ['id_codigo'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorios',
            fields=[
                ('id_recordatorio', models.AutoField(primary_key=True, serialize=False)),
                ('fch_recordatorio', models.DateField()),
                ('hora_recordatorio', models.TimeField()),
                ('descripción', models.TextField()),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Clientes')),
            ],
            options={
                'verbose_name_plural': 'Recordatorios Cliente',
                'ordering': ['id_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Promesas',
            fields=[
                ('id_promesa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('valor', models.IntegerField()),
                ('estatus_promesa', models.CharField(choices=[('1', 'Pendiente'), ('2', 'Cumplida'), ('3', 'Incumplida')], default='1', max_length=1, verbose_name='Estatus de la Promesa')),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('usuario_creacion', models.IntegerField()),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Clientes')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Usuarios')),
            ],
            options={
                'verbose_name_plural': 'Promesas',
                'ordering': ['id_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('valor', models.IntegerField()),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('usuario_creacion', models.IntegerField()),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Clientes')),
                ('id_promesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Promesas')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Usuarios')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
                'ordering': ['id_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Motivos',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripción', models.CharField(max_length=100)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('id_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Codigos')),
            ],
            options={
                'verbose_name_plural': 'Motivos',
                'ordering': ['id_motivo'],
            },
        ),
        migrations.CreateModel(
            name='Gestiones',
            fields=[
                ('id_gestion', models.AutoField(primary_key=True, serialize=False)),
                ('fch_gestion', models.DateTimeField(auto_now_add=True)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('usuario_creacion', models.IntegerField()),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Clientes')),
                ('id_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Codigos')),
                ('id_motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Motivos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Usuarios')),
            ],
            options={
                'verbose_name_plural': 'Gestiones',
                'ordering': ['fch_gestion'],
            },
        ),
    ]
