# Generated by Django 3.0.8 on 2020-08-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCobros', '0011_logcobros'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='id_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gestionCobros.Clientes'),
            preserve_default=False,
        ),
    ]
