# Generated by Django 3.0.8 on 2020-08-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCobros', '0012_contactos_id_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='mora_actual',
            new_name='dias_mora',
        ),
        migrations.AddField(
            model_name='productos',
            name='saldo_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
