# Generated by Django 3.0.8 on 2020-08-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCobros', '0013_auto_20200802_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fch_ultimo_acceso',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='ip_ultimo_acceso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='primer_apellido',
            field=models.CharField(max_length=35, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='primer_nombre',
            field=models.CharField(max_length=35, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=35, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=35, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.CharField(max_length=20, verbose_name='Usuario'),
        ),
    ]
