# Generated by Django 3.0.8 on 2020-08-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCobros', '0014_auto_20200806_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usuario_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
